apiVersion: v1
kind: Service
metadata:
  name: hello-counter
  labels:
    app: hello-counter
spec:
  ports:
  - port: 80 
    targetPort: 5000
    name: http 
  selector:
    app: hello-counter
  type: LoadBalancer 
  sessionAffinity: None
