apiVersion: v1
kind: Pod
metadata:
  name: hello-counter 
  labels:
    app: hello-counter
    version: 1.0
spec:
  containers:
    - name: hello-counter
      image: elsonrodriguez/hello-counter:1.0 
      ports:
        - containerPort: 5000 
      resources:
        limits:
          memory: "50Mi"
          cpu: ".1"
      livenessProbe:
        httpGet:
          path: /check
          port: 5000
        initialDelaySeconds: 5
        timeoutSeconds: 1
      readinessProbe:
        httpGet:
          path: /check
          port: 5000
        initialDelaySeconds: 5
        timeoutSeconds: 1
