apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-counter 
  labels:
    app: hello-counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-counter
    spec:
      containers:
      - name: hello-counter
        image: elsonrodriguez/hello-counter:1.0 
        env:
          - name: REDIS_HOST
            value: "redis"
        ports:
          - containerPort: 5000
        resources:
          limits:
            memory: "50Mi"
            cpu: ".1"
        livenessProbe:
          httpGet:
            path: /check
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /check
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 1
