apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: redis 
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.1
        - args:
          - redis-server
          - --appendonly yes
        ports:
          - containerPort: 6379
        resources:
          limits:
            memory: "300Mi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data/
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis
