kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata: 
  name: "redis"
  annotations: 
    volume.alpha.kubernetes.io/storage-class: "redis"
spec: 
  accessModes: 
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
